#!/bin/bash

#Author: CipherWar
#Date Created: 04/03/26
#Date Modified: 04/03/26
#Description:

clear
wi=`whoami`
if [ -e /home/$wi/error.txt ] 
then 
  echo File exists
else
  echo File does not exist
fi

