#!/bin/bash

#Author: CipherWar
#Date Created: 04/03/26
#Date Modified: 04/03/26
#Description:

echo What is your name?
read b
echo
echo What is your profession?
read c
echo
echo What is your fav show?
read d
echo
echo Hello $b
echo Your profession $c is awesome!
echo $d is good show

